<a href="https://colab.research.google.com/github/mohit-kumar396/Data-Analysis-Projects/blob/main/1_Product_profitability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("profit.csv")

In [ ]:
df.shape

(20, 4)

In [ ]:
df.head()

      Product     Category     CP     SP
0  Smartphone  Electronics  22000  26400
1      Laptop  Electronics  55000  63250
2      Tablet  Electronics  18000  19800
3  Smartwatch  Electronics   6500   5850
4  Headphones  Electronics   2000   2400

In [ ]:
# Concise Information about Data.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   20 non-null     object
 1   Category  20 non-null     object
 2   CP        20 non-null     int64
 3   SP        20 non-null     int64
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

In [ ]:
# Statistical information about numerical column.

In [ ]:
df.describe()

                 CP            SP
count     20.000000     20.000000
mean    7785.000000   8591.750000
std    12724.490477  14574.987702
min      500.000000    650.000000
25%     1175.000000   1365.000000
50%     2800.000000   3360.000000
75%     7400.000000   8190.000000
max    55000.000000  63250.000000

In [ ]:
df["Category"].value_counts()

Category
Electronics    12
Fashion         3
Furniture       3
Accessories     2
Name: count, dtype: int64

In [ ]:
# Q1. Prfit/loss on each product

df["profit_loss"] = df["SP"] - df["CP"]
df
# Positive Value=profit
# Negative Value = Loss
# 0 = No profit no loss

              Product     Category     CP     SP  profit_loss
0          Smartphone  Electronics  22000  26400         4400
1              Laptop  Electronics  55000  63250         8250
2              Tablet  Electronics  18000  19800         1800
3          Smartwatch  Electronics   6500   5850         -650
4          Headphones  Electronics   2000   2400          400
5            Backpack  Accessories   1400   1820          420
6       Running Shoes      Fashion   2800   3360          560
7              Jacket      Fashion   4200   3780         -420
8             T-Shirt      Fashion    750    975          225
9        Office Chair    Furniture   6800   8160         1360
10        Study Table    Furniture   9200   8280         -920
11          Desk Lamp    Furniture   1100   1430          330
12       Water Bottle  Accessories    550    660          110
13         Power Bank  Electronics   1800   2070          270
14  Bluetooth Speaker  Electronics   3200   3840          640
15           Keyboard  Electronics   1200   1080         -120
16     Wireless Mouse  Electronics    500    650          150
17             Webcam  Electronics   2800   3360          560
18            Printer  Electronics  15000  13500        -1500
19            USB Hub  Electronics    900   1170          270

In [ ]:
# Q2. Prfit_percent/loss_percent on each product

df["profit_loss_percent"] = (df["profit_loss"]/df["CP"]) * 100
df

,Product,Category,CP,SP,profit_loss,profit_loss_percent
0,Smartphone,Electronics,22000,26400,4400,20.0
1,Laptop,Electronics,55000,63250,8250,15.0
2,Tablet,Electronics,18000,19800,1800,10.0
3,Smartwatch,Electronics,6500,5850,-650,-10.0
4,Headphones,Electronics,2000,2400,400,20.0
5,Backpack,Accessories,1400,1820,420,30.0
6,Running Shoes,Fashion,2800,3360,560,20.0
7,Jacket,Fashion,4200,3780,-420,-10.0
8,T-Shirt,Fashion,750,975,225,30.0
9,Office Chair,Furniture,6800,8160,1360,20.0
10,Study Table,Furniture,9200,8280,-920,-10.0
11,Desk Lamp,Furniture,1100,1430,330,30.0
12,Water Bottle,Accessories,550,660,110,20.0
13,Power Bank,Electronics,1800,2070,270,15.0
14,Bluetooth Speaker,Electronics,3200,3840,640,20.0
15,Keyboard,Electronics,1200,1080,-120,-10.0
16,Wireless Mouse,Electronics,500,650,150,30.0
17,Webcam,Electronics,2800,3360,560,20.0
18,Printer,Electronics,15000,13500,-1500,-10.0
19,USB Hub,Electronics,900,1170,270,30.0

In [ ]:
# Q3. product corresponding to the maximum Profit_Loss value.

df.loc[df["profit_loss"].idxmax(), "Product"]

# Syntax Of the above code
# DataFrame.loc[DataFrame["column"].idxmax(), "target_column"]
# df["Profit_Loss"].idxmax() :- Profit_Loss column mein maximum value ka index label return karta hai.
# df.loc[index, "Product"] :- us index ki "Product" value return karta hai.

'Laptop'

In [ ]:
# Q4. Entire row for the product corresponding to maximum profit_Loss value

df.loc[df["profit_loss"].idxmax()]

Product                     Laptop
Category               Electronics
CP                           55000
SP                           63250
profit_loss                   8250
profit_loss_percent           15.0
Name: 1, dtype: object

In [ ]:
# Lowest profit / biggest loss

df.loc[df["profit_loss"].idxmin(), ["Product", "profit_loss"]]

Product        Printer
profit_loss      -1500
Name: 18, dtype: object

In [ ]:
df

,Product,Category,CP,SP,profit_loss,profit_loss_percent
0,Smartphone,Electronics,22000,26400,4400,20.0
1,Laptop,Electronics,55000,63250,8250,15.0
2,Tablet,Electronics,18000,19800,1800,10.0
3,Smartwatch,Electronics,6500,5850,-650,-10.0
4,Headphones,Electronics,2000,2400,400,20.0
5,Backpack,Accessories,1400,1820,420,30.0
6,Running Shoes,Fashion,2800,3360,560,20.0
7,Jacket,Fashion,4200,3780,-420,-10.0
8,T-Shirt,Fashion,750,975,225,30.0
9,Office Chair,Furniture,6800,8160,1360,20.0
10,Study Table,Furniture,9200,8280,-920,-10.0
11,Desk Lamp,Furniture,1100,1430,330,30.0
12,Water Bottle,Accessories,550,660,110,20.0
13,Power Bank,Electronics,1800,2070,270,15.0
14,Bluetooth Speaker,Electronics,3200,3840,640,20.0
15,Keyboard,Electronics,1200,1080,-120,-10.0
16,Wireless Mouse,Electronics,500,650,150,30.0
17,Webcam,Electronics,2800,3360,560,20.0
18,Printer,Electronics,15000,13500,-1500,-10.0
19,USB Hub,Electronics,900,1170,270,30.0

In [ ]:
# Q5. product corresponding to the maximum Profit_Loss_percent value.

df.loc[df["profit_loss_percent"].idxmax(), "Product"]

'Backpack'

In [ ]:
df.loc[df["profit_loss_percent"].idxmax()]

Product                   Backpack
Category               Accessories
CP                            1400
SP                            1820
profit_loss                    420
profit_loss_percent           30.0
Name: 5, dtype: object

In [ ]:
# Q6. Number of products which are profitable.

(df["profit_loss"] > 0).sum()

np.int64(15)

In [ ]:
# Q7. Number of product which are not profitable

(df["profit_loss"]<=0).sum()

np.int64(5)

In [ ]:
# Q8. Total Investement

Total_Investment = df["CP"].sum()
Total_Investment

np.int64(155700)

In [ ]:
# Q9. Total Revenue Generted

Total_Revenue = df["SP"].sum()
Total_Revenue

np.int64(171835)

In [ ]:
# Q10. Net profit/loss

Net_profit_loss= df["profit_loss"].sum()
Net_profit_loss

np.int64(16135)

In [ ]:
# Q11. Lets increase sp by 10% and see what will be the net_profit?

df["new_sp"]=df["SP"] * 1.1
df["new_profit_loss"]=df["new_sp"]-df["CP"]
new_net_profit_loss= df["new_profit_loss"].sum()
new_net_profit_loss

np.float64(33318.50000000001)

In [ ]:
# Q12. Overall profit increase after increasing sp by 10% is
new_profit_increase=new_net_profit_loss-Net_profit_loss
new_profit_increase

np.float64(17183.500000000007)

In [ ]:
# Q13. Which product should the company on?
# Here there is two metrics to consider
# 1. profi_loss
# 2. profit_loss_percent
df.sort_values(["profit_loss"], ascending=False)

,Product,Category,CP,SP,profit_loss,profit_loss_percent,new_sp,new_profit_loss
1,Laptop,Electronics,55000,63250,8250,15.0,69575.0,14575.0
0,Smartphone,Electronics,22000,26400,4400,20.0,29040.0,7040.0
2,Tablet,Electronics,18000,19800,1800,10.0,21780.0,3780.0
9,Office Chair,Furniture,6800,8160,1360,20.0,8976.0,2176.0
14,Bluetooth Speaker,Electronics,3200,3840,640,20.0,4224.0,1024.0
17,Webcam,Electronics,2800,3360,560,20.0,3696.0,896.0
6,Running Shoes,Fashion,2800,3360,560,20.0,3696.0,896.0
5,Backpack,Accessories,1400,1820,420,30.0,2002.0,602.0
4,Headphones,Electronics,2000,2400,400,20.0,2640.0,640.0
11,Desk Lamp,Furniture,1100,1430,330,30.0,1573.0,473.0
13,Power Bank,Electronics,1800,2070,270,15.0,2277.0,477.0
19,USB Hub,Electronics,900,1170,270,30.0,1287.0,387.0
8,T-Shirt,Fashion,750,975,225,30.0,1072.5,322.5
16,Wireless Mouse,Electronics,500,650,150,30.0,715.0,215.0
12,Water Bottle,Accessories,550,660,110,20.0,726.0,176.0
15,Keyboard,Electronics,1200,1080,-120,-10.0,1188.0,-12.0
7,Jacket,Fashion,4200,3780,-420,-10.0,4158.0,-42.0
3,Smartwatch,Electronics,6500,5850,-650,-10.0,6435.0,-65.0
10,Study Table,Furniture,9200,8280,-920,-10.0,9108.0,-92.0
18,Printer,Electronics,15000,13500,-1500,-10.0,14850.0,-150.0

In [ ]:
# 2.
df.sort_values(["profit_loss_percent"], ascending=False)

,Product,Category,CP,SP,profit_loss,profit_loss_percent,new_sp,new_profit_loss
19,USB Hub,Electronics,900,1170,270,30.0,1287.0,387.0
11,Desk Lamp,Furniture,1100,1430,330,30.0,1573.0,473.0
8,T-Shirt,Fashion,750,975,225,30.0,1072.5,322.5
5,Backpack,Accessories,1400,1820,420,30.0,2002.0,602.0
16,Wireless Mouse,Electronics,500,650,150,30.0,715.0,215.0
14,Bluetooth Speaker,Electronics,3200,3840,640,20.0,4224.0,1024.0
12,Water Bottle,Accessories,550,660,110,20.0,726.0,176.0
0,Smartphone,Electronics,22000,26400,4400,20.0,29040.0,7040.0
17,Webcam,Electronics,2800,3360,560,20.0,3696.0,896.0
6,Running Shoes,Fashion,2800,3360,560,20.0,3696.0,896.0
9,Office Chair,Furniture,6800,8160,1360,20.0,8976.0,2176.0
4,Headphones,Electronics,2000,2400,400,20.0,2640.0,640.0
1,Laptop,Electronics,55000,63250,8250,15.0,69575.0,14575.0
13,Power Bank,Electronics,1800,2070,270,15.0,2277.0,477.0
2,Tablet,Electronics,18000,19800,1800,10.0,21780.0,3780.0
3,Smartwatch,Electronics,6500,5850,-650,-10.0,6435.0,-65.0
10,Study Table,Furniture,9200,8280,-920,-10.0,9108.0,-92.0
7,Jacket,Fashion,4200,3780,-420,-10.0,4158.0,-42.0
15,Keyboard,Electronics,1200,1080,-120,-10.0,1188.0,-12.0
18,Printer,Electronics,15000,13500,-1500,-10.0,14850.0,-150.0

In [ ]:
# Insight is:-
# Laptop is more valuable in terms of absolute profit,
# while Backpack, USB Hub, Desk Lamp, T-Shirt	 is more efficient and same in terms of profitability percentage.

In [ ]:
# If the goal is maximum profit amount, focus more on Laptop.
#If the goal is better profit margin, Backpack, USB Hub, Desk Lamp, T-Shirt is better.
# If Backpack, USB Hub, Desk Lamp, T-Shirt sells in large quantities, its total profit can become very significant.

In [ ]:
# Final Insight:-

# "Laptop has the highest absolute profit, but Backpack, USB Hub, Desk Lamp, T-Shirt has a higher profit margin.
# This suggests that Laptop generates more profit per unit,
# while Backpack, USB Hub, Desk Lamp, T-Shirt provides better profitability relative to its cost."

In [ ]:
# High profit + high sales → ⭐ Strong product
# High profit % + high sales → ⭐ Strong and efficient product
# High profit but low sales → Try increasing sales
# High profit % but low sales → Try increasing demand/sales
# Low profit + low sales → Consider improving or dropping the product

In [ ]:
# Q14. Product whose profit> 500

df.loc[df["profit_loss"]>500, ["Product", "profit_loss"]]

              Product  profit_loss
0          Smartphone         4400
1              Laptop         8250
2              Tablet         1800
6       Running Shoes          560
9        Office Chair         1360
14  Bluetooth Speaker          640
17             Webcam          560

In [ ]:
# Q15. Category wise product sale

df.groupby("Category")["Product"].count()

# Syntax of groupby():-
# df.groupby("column_name")["column_to_aggregate"].aggregation_function()

Category
Accessories     2
Electronics    12
Fashion         3
Furniture       3
Name: Product, dtype: int64

In [ ]:
# Q16. Category-wise profit

df.groupby("Category")["profit_loss"].agg(["sum", "mean"])

# .agg is used to apply multiple aggregate function

               sum         mean
Category
Accessories    530   265.000000
Electronics  14470  1205.833333
Fashion        365   121.666667
Furniture      770   256.666667

In [ ]:
# Q17. Category With Highest Average profit percent

df.groupby("Category")["profit_loss_percent"].mean()

# This tells Which category has better average profitability?

Category
Accessories    25.000000
Electronics    12.500000
Fashion        13.333333
Furniture      13.333333
Name: profit_loss_percent, dtype: float64

In [ ]:
# lets do:- sql analysis in the same data set:-

In [ ]:
import pandas as pd
import sqlite3
profit_loss_df=pd.read_csv("profit.csv")
conn=sqlite3.connect(":memory:")

In [ ]:
profit_loss_df.to_sql("profit", conn,index=False, if_exists="replace")
df

,Product,Category,CP,SP,profit_loss,profit_loss_percent,new_sp,new_profit_loss
0,Smartphone,Electronics,22000,26400,4400,20.0,29040.0,7040.0
1,Laptop,Electronics,55000,63250,8250,15.0,69575.0,14575.0
2,Tablet,Electronics,18000,19800,1800,10.0,21780.0,3780.0
3,Smartwatch,Electronics,6500,5850,-650,-10.0,6435.0,-65.0
4,Headphones,Electronics,2000,2400,400,20.0,2640.0,640.0
5,Backpack,Accessories,1400,1820,420,30.0,2002.0,602.0
6,Running Shoes,Fashion,2800,3360,560,20.0,3696.0,896.0
7,Jacket,Fashion,4200,3780,-420,-10.0,4158.0,-42.0
8,T-Shirt,Fashion,750,975,225,30.0,1072.5,322.5
9,Office Chair,Furniture,6800,8160,1360,20.0,8976.0,2176.0
10,Study Table,Furniture,9200,8280,-920,-10.0,9108.0,-92.0
11,Desk Lamp,Furniture,1100,1430,330,30.0,1573.0,473.0
12,Water Bottle,Accessories,550,660,110,20.0,726.0,176.0
13,Power Bank,Electronics,1800,2070,270,15.0,2277.0,477.0
14,Bluetooth Speaker,Electronics,3200,3840,640,20.0,4224.0,1024.0
15,Keyboard,Electronics,1200,1080,-120,-10.0,1188.0,-12.0
16,Wireless Mouse,Electronics,500,650,150,30.0,715.0,215.0
17,Webcam,Electronics,2800,3360,560,20.0,3696.0,896.0
18,Printer,Electronics,15000,13500,-1500,-10.0,14850.0,-150.0
19,USB Hub,Electronics,900,1170,270,30.0,1287.0,387.0

In [ ]:
# Q1. Display all products with their Category, Cost Price, Selling Price

In [ ]:
query1="""
select p.category, p.CP, p.SP
from profit p
"""
result=pd.read_sql_query(query1, conn)
result

       Category     CP     SP
0   Electronics  22000  26400
1   Electronics  55000  63250
2   Electronics  18000  19800
3   Electronics   6500   5850
4   Electronics   2000   2400
5   Accessories   1400   1820
6       Fashion   2800   3360
7       Fashion   4200   3780
8       Fashion    750    975
9     Furniture   6800   8160
10    Furniture   9200   8280
11    Furniture   1100   1430
12  Accessories    550    660
13  Electronics   1800   2070
14  Electronics   3200   3840
15  Electronics   1200   1080
16  Electronics    500    650
17  Electronics   2800   3360
18  Electronics  15000  13500
19  Electronics    900   1170

In [ ]:
# Q2. Find all products that belong to the Electronics category.

In [ ]:
query2="""
select p.Product as Electronic_product
from profit p
where p.Category="Electronics"
"""
result=pd.read_sql_query(query2, conn)
result

   Electronic_product
0          Smartphone
1              Laptop
2              Tablet
3          Smartwatch
4          Headphones
5          Power Bank
6   Bluetooth Speaker
7            Keyboard
8      Wireless Mouse
9              Webcam
10            Printer
11            USB Hub

In [ ]:
# Q3. Find all products where the Selling Price is greater than the Cost Price.

In [ ]:
query3="""
select p.Product as Product_with_SP_greater_than_CP
from profit p
where p.SP>p.CP
"""
result=pd.read_sql_query(query3, conn)
result

   Product_with_SP_greater_than_CP
0                       Smartphone
1                           Laptop
2                           Tablet
3                       Headphones
4                         Backpack
5                    Running Shoes
6                          T-Shirt
7                     Office Chair
8                        Desk Lamp
9                     Water Bottle
10                      Power Bank
11               Bluetooth Speaker
12                  Wireless Mouse
13                          Webcam
14                         USB Hub

In [ ]:
#Q4. Find all products where the Selling Price is less than the Cost Price.

In [ ]:
query4="""
select p.Product as Product_with_SP_less_than_CP
from profit p
where p.SP<p.CP
"""
result=pd.read_sql_query(query4, conn)
result

  Product_with_SP_less_than_CP
0                   Smartwatch
1                       Jacket
2                  Study Table
3                     Keyboard
4                      Printer

In [ ]:
# Q5.Display all products in descending order of Selling Price.

In [ ]:
query5="""
select p.Product as Product_in_descending_order_of_SP
from profit p
order by p.SP desc
"""
result=pd.read_sql_query(query5, conn)
result

   Product_in_descending_order_of_SP
0                             Laptop
1                         Smartphone
2                             Tablet
3                            Printer
4                        Study Table
5                       Office Chair
6                         Smartwatch
7                  Bluetooth Speaker
8                             Jacket
9                      Running Shoes
10                            Webcam
11                        Headphones
12                        Power Bank
13                          Backpack
14                         Desk Lamp
15                           USB Hub
16                          Keyboard
17                           T-Shirt
18                      Water Bottle
19                    Wireless Mouse